
#ifndef WORDS_DATA_H
#define WORDS_DATA_H
QMap<QString, QStringList> groupMap {
{"01 - Kanji 1-4", {"one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten", "river", "mountain", "earth", "fire", "tree", "water"}},
{"02 - Kanji 5-9", {"day", "money", "rain", "yen", "north", "south", "east", "west", "one day", "two days", "three days", "four days", "five days", "six days", "seven days", "eight days", "nine days", "ten days", "twenty days"}},
{"03 - Kanji 10-13", {"one counter", "two counter", "three counter", "four counter", "five counter", "six counter", "seven counter", "eight counter", "nine counter", "white", "100", "1000", "10000", "big", "small"}},
{"98 - The Body", {"mouth", "eye", "ear", "nose", "face", "hand", "foot", "finger", "head", "tooth"}},
{"99 - Bed and Bath", {"pillow", "bed", "futon", "blanket", "towel", "bath", "soap", "toothbrush", "mirror", "window"}}
};
QMap<QString, QStringList> ansMap {
{"one", {"one", "ichi", "いち", "一"}},
{"two", {"two", "ni", "に", "二"}},
{"three", {"three", "san", "さん", "三"}},
{"four", {"four", "yon", "よん", "四"}},
{"five", {"five", "go", "ご", "五"}},
{"six", {"six", "roku", "ろく", "六"}},
{"seven", {"seven", "nana", "なな", "七"}},
{"eight", {"eight", "hachi", "はち", "八"}},
{"nine", {"nine", "kyuu", "きゅう", "九"}},
{"ten", {"ten", "juu", "じゅう", "十"}},
{"river", {"river", "kawa", "かわ", "川"}},
{"mountain", {"mountain", "yama", "やま", "山"}},
{"earth", {"earth", "tsuchi", "つち", "土"}},
{"fire", {"fire", "hi", "ひ", "火"}},
{"tree", {"tree", "ki", "き", "木"}},
{"water", {"water", "mizu", "みず", "水"}},
{"day", {"day", "hi", "ひ", "日"}},
{"money", {"money", "okane", "おかね", "お金"}},
{"rain", {"rain", "ame", "あめ", "雨"}},
{"yen", {"yen", "en", "えん", "円"}},
{"north", {"north", "kita", "きた", "北"}},
{"south", {"south", "minami", "みなみ", "南"}},
{"east", {"east", "higashi", "ひがし", "東"}},
{"west", {"west", "nishi", "にし", "西"}},
{"one day", {"one day", "ichinichi", "いちにち", "一日"}},
{"two days", {"two days", "futsuka", "ふつか", "二日"}},
{"three days", {"three days", "mikka", "みっか", "三日"}},
{"four days", {"four days", "yokka", "よっか", "四日"}},
{"five days", {"five days", "itsuka", "いつか", "五日"}},
{"six days", {"six days", "muika", "むいか", "六日"}},
{"seven days", {"seven days", "nanoka", "なのか", "七日"}},
{"eight days", {"eight days", "youka", "ようか", "八日"}},
{"nine days", {"nine days", "kokonoka", "ここのか", "九日"}},
{"ten days", {"ten days", "tooka", "とおか", "十日"}},
{"twenty days", {"twenty days", "hatsuka", "はつか", "二十日"}},
{"one counter", {"one counter", "hitotsu", "ひとつ", "一つ"}},
{"two counter", {"two counter", "futatsu", "ふたつ", "二つ"}},
{"three counter", {"three counter", "mittsu", "みっつ", "三つ"}},
{"four counter", {"four counter", "yottsu", "よっつ", "四つ"}},
{"five counter", {"five counter", "itsutsu", "いつつ", "五つ"}},
{"six counter", {"six counter", "muttsu", "むっつ", "六つ"}},
{"seven counter", {"seven counter", "nanatsu", "ななつ", "七つ"}},
{"eight counter", {"eight counter", "yattsu", "やっつ", "八つ"}},
{"nine counter", {"nine counter", "kokonotsu", "ここのつ", "九つ"}},
{"white", {"white", "shiro", "しろ", "白"}},
{"100", {"100", "hyaku", "ひゃく", "百"}},
{"1000", {"1000", "sen", "せん", "千"}},
{"10000", {"10000", "man", "まん", "万"}},
{"big", {"big", "ookii", "おおきい", "大きい"}},
{"small", {"small", "chiisai", "ちいさい", "小さい"}},
{"mouth", {"mouth", "kuchi", "くち", "口"}},
{"eye", {"eye", "me", "め", "目"}},
{"ear", {"ear", "mimi", "みみ", "耳"}},
{"nose", {"nose", "hana", "はな", "鼻"}},
{"face", {"face", "kao", "かお", "顔"}},
{"hand", {"hand", "te", "て", "手"}},
{"foot", {"foot", "ashi", "あし", "足"}},
{"finger", {"finger", "yubi", "ゆび", "指"}},
{"head", {"head", "atama", "あたま", "頭"}},
{"tooth", {"tooth", "ha", "は", "歯"}},
{"pillow", {"pillow", "makura", "まくら", "枕"}},
{"bed", {"bed", "beddo", "ベッド", "ベッド"}},
{"futon", {"futon", "futon", "ふとん", "布団"}},
{"blanket", {"blanket", "moufu", "もうふ", "毛布"}},
{"towel", {"towel", "taoru", "タオル", "タオル"}},
{"bath", {"bath", "ofuro", "おふろ", "お風呂"}},
{"soap", {"soap", "sekken", "せっけん", "石けん"}},
{"toothbrush", {"toothbrush", "haburashi", "ハブラシ", "歯ブラシ"}},
{"mirror", {"mirror", "kagami", "かがみ", "鏡"}},
{"window", {"window", "mado", "まど", "窓"}}
};
#endif // WORDS_DATA_H